# Generated by Django 6.0.6 on 2026-07-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
