# Generated by Django 6.0.6 on 2026-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='require_photo',
            field=models.BooleanField(default=False),
        ),
    ]
